// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBltqMlJ8e8_dOuHvLkIs6xLFIh7qVcX24',
    appId: '1:500529511806:web:3c08c1812c377ac465072f',
    messagingSenderId: '500529511806',
    projectId: 'campus-recruitment-d8aad',
    authDomain: 'campus-recruitment-d8aad.firebaseapp.com',
    storageBucket: 'campus-recruitment-d8aad.appspot.com',
    measurementId: 'G-GMQX6B7Y9C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDypdhw6qkLUwQdY7VIQhYVrppKm-DegLM',
    appId: '1:500529511806:android:25ff1fafe71b9c8d65072f',
    messagingSenderId: '500529511806',
    projectId: 'campus-recruitment-d8aad',
    storageBucket: 'campus-recruitment-d8aad.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCjFd-AI5XfOBHF5BA-S5dK94KLZ5ebiWU',
    appId: '1:500529511806:ios:e3d529ca92f8cd4165072f',
    messagingSenderId: '500529511806',
    projectId: 'campus-recruitment-d8aad',
    storageBucket: 'campus-recruitment-d8aad.appspot.com',
    iosBundleId: 'com.example.campusRecruitment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCjFd-AI5XfOBHF5BA-S5dK94KLZ5ebiWU',
    appId: '1:500529511806:ios:3ae756f861f2b82b65072f',
    messagingSenderId: '500529511806',
    projectId: 'campus-recruitment-d8aad',
    storageBucket: 'campus-recruitment-d8aad.appspot.com',
    iosBundleId: 'com.example.campusRecruitment.RunnerTests',
  );
}
